# Use postgres/example user/password credentials
version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - link-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
volumes:
  link-db:
    driver: local